apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-instrumentation
  namespace: example-project-dev
spec:
  exporter:
    endpoint: http://opentelemetry-collector.monitoring.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: always_on
  java:
    env:
      - name: OTEL_SEMCONV_STABILITY_OPT_IN
        value: database
