apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: example-project-dev

images:
  - name: registry.gitlab.com/jjsiv-homelab/welcome-app/hello-server
    newTag: latest
