apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/
  - postgres.yaml

patches:
  - path: deplyoment-patch.yaml

secretGenerator:
  - name: postgres-secret
    literals:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nameserver
    options:
      disableNameSuffixHash: true

namespace: example-project-dev

images:
  - name: registry.gitlab.com/jjsiv-homelab/welcome-app/name-server
    newTag: latest
