apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

replicas:
  - name: example-go-app
    count: 3

images:
  - name: ghcr.io/jjsiv-homelab/example-go-app
    newTag: v1.0.2
